apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firs-replicaset
  labels:
    apps: myapp
spec:
  selector:
    matchLabels:
      apps: myapp
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
      - name: nginx-2
        image: nginx
        resources:
        ports:
          - containerPort: 80