apiVersion: apps/v1
kind: Deployment
metadata:
  name: canbo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      name: canbo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: canbo-app
    spec:
      containers:
      - name: canbo-app
        image: nginx
        resources:
        ports:
          - containerPort: 80