apiVersion: v1
kind: Pod
metadata:
  name: canbo-app
  labels:
    name: canbo-app
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              operator: In
              values:
                - "blue" 
  containers:
  - name: canbo-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
